#ifndef ROSALIA_ARRAYLIST_H_INCLUDE
#define ROSALIA_ARRAYLIST_H_INCLUDE

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ROSALIA_ARRAYLIST_STATIC
#define ROSALIA__ARRAYLIST_DEC static
#define ROSALIA__ARRAYLIST_DEC_EXT static
#define ROSALIA__ARRAYLIST_DEF static
#else
#define ROSALIA__ARRAYLIST_DEC
#define ROSALIA__ARRAYLIST_DEC_EXT extern
#define ROSALIA__ARRAYLIST_DEF
#endif

#define ROSALIA_ARRAYLIST_VERSION_MAJOR 0
#define ROSALIA_ARRAYLIST_VERSION_MINOR 0
#define ROSALIA_ARRAYLIST_VERSION_PATCH 0

#ifdef __cplusplus
extern "C" {
#endif

#ifndef ROSALIA_ARRAYLIST_NO_SHORT_NAMES
#define ARRAYLIST ROSA_ARRAYLIST
#define ALIST_CREATE ROSA_ARRAYLIST_CREATE
#define ALIST_DESTROY ROSA_ARRAYLIST_DESTROY // this one doesn't need to be a macro
#define ALIST_CAP ROSA_ARRAYLIST_CAP // this one doesn't need to be a macro
#define ALIST_SETCAP ROSA_ARRAYLIST_SETCAP
#define ALIST_FITCAP ROSA_ARRAYLIST_FITCAP
#define ALIST_LEN ROSA_ARRAYLIST_LEN // this one doesn't need to be a macro
#define ALIST_SETLEN ROSA_ARRAYLIST_SETLEN
#define ALIST_FITLEN ROSA_ARRAYLIST_FITLEN
#define ALIST_ADDLEN_IDX ROSA_ARRAYLIST_ADDLEN_IDX
#define ALIST_ADDLEN_PTR ROSA_ARRAYLIST_ADDLEN_PTR
#define ALIST_PUSH ROSA_ARRAYLIST_PUSH
#define ALIST_PUSH_N ROSA_ARRAYLIST_PUSH_N
#define ALIST_POP ROSA_ARRAYLIST_POP
#define ALIST_POP_N ROSA_ARRAYLIST_POP_N
#define ALIST_PEEK ROSA_ARRAYLIST_PEEK
#define ALIST_INSERT ROSA_ARRAYLIST_INSERT
#define ALIST_INSERT_N ROSA_ARRAYLIST_INSERT_N
#define ALIST_REMOVE ROSA_ARRAYLIST_REMOVE
#define ALIST_REMOVE_N ROSA_ARRAYLIST_REMOVE_N
#define ALIST_REMOVE_SWAP ROSA_ARRAYLIST_REMOVE_SWAP
#define ALIST_REMOVE_SWAP_N ROSA_ARRAYLIST_REMOVE_SWAP_N
#define ALIST_LAST ROSA_ARRAYLIST_LAST
#define ALIST_CLONE ROSA_ARRAYLIST_CLONE
#endif

#ifdef __cplusplus
}
#endif

#endif

#if defined(ROSALIA_ARRAYLIST_IMPLEMENTATION) && !defined(ROSALIA_ARRAYLIST_H_IMPL)
#define ROSALIA_ARRAYLIST_H_IMPL

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif
